version: '2'

services:
  worker1:
    build:
      context: worker1/
    ports:
      - "5000:5000"
    networks:
      bayesdistributed:
        ipv4_address: 172.21.0.2

  worker2:
    build:
      context: worker2/
    ports:
      - "5001:5000"
    networks:
      bayesdistributed:
        ipv4_address: 172.21.0.3

  worker3:
    build:
      context: worker3/
    ports:
      - "5002:5000"
    networks:
      bayesdistributed:
        ipv4_address: 172.21.0.4

  master:
    build:
      context: master/
    ports:
      - "5003:5000"
    networks:
      bayesdistributed:
        ipv4_address: 172.21.0.5

networks:
  bayesdistributed:
    driver: bridge
    ipam:
     config:
       - subnet: 172.21.0.0/16
         gateway: 172.21.0.1

